/*
 * address_code.h
 *
 *  Created on: Mar 27, 2012
 *      Author: SebastianN
 */
#ifndef __ADDRESSCODE_HEADER__
#define __ADDRESSCODE_HEADER__

#include "types.h"
#include "symboltable.h"

void emit(string); //<*AUTOGENERATED LINE*> STATEMENT
void backpatch(int,int); //Zeile,

/**
 * @brief Converts an IRCode into a string
 */
string IRtoString();
char* OpToString( char*,irCode_t*,int);
void printParam( irCode_t* );
/**
 * @brief Real conversion from expressions to IRCode
 */
void createIRCodeFromExpr(expr_t,int,expr_t);
irCode_t* getIRCode();

#endif
