/*
 * address_code.h
 *
 *  Created on: Mar 27, 2012
 *      Author: SebastianN
 */
#ifndef __ADDRESSCODE_HEADER__
#define __ADDRESSCODE_HEADER__

void emit(string); //<*AUTOGENERATED LINE*> STATEMENT
void backpatch(int,int); //Zeile,

#endif
